$ \huge{solution \ \ of \ \ 2.1}$

let $x_i$  be indicator variable such that $x_i$= 1 if we choose $c_i$ course
   
 $x_i$= 0 otherwise here i = 0,1,2,3,4,5,6,7,8,9

$ c_0 = 4 \  \ \  c_1 = 3 \ \ \ c_2 =6  \ \ \ c_3 = 5 \ \ \ c_4 =2 \ \ \ c_5 = 6 \ \ \ c_6 = 4 \ \ c_7 = 8 \ \ c_8 = 8 \ \  c_9 = 6$ 

max $ \sum  c_ix_i \ \ \ \ \ \ \ \ \ \ \ i=0,1,2,3,4,5,6,7,8,9$ \\
subject to constraints \\
$ \sum c_ix_i \ge 26$ 

 $4 \le \sum x_i \le 8 $

i = 0,1,2,3,4,5,6,7,8,9


$ x_2+x_7 \le 1$

$ x_1+x_9 \le 1$

$ x_2 + x_8 \le 1$

$ 1 \le x_0+x_1+x_2+x_3 \le 2$

$ x_5+x_9 \le 1 $

$x_6+x_8+x_9 \le 2 $

$ x_9-x_4 \le 0 $

In [1]:
!pip install -q pyomo

     |████████████████████████████████| 9.7 MB 5.2 MB/s 
     |████████████████████████████████| 49 kB 6.3 MB/s 


In [2]:
from pyomo.environ import *

In [3]:
import numpy as np

In [4]:
model = ConcreteModel()

In [5]:
M = 9
N = 10
obj_coef=np.array([4,3,6,5,2,6,4,8,8,6])
constr_coef = np.array([[4,3,6,5,2,6,4,8,8,6],[1,1,1,1,1,1,1,1,1,1],[0,0,1,0,0,0,0,1,0,0],[0,1,0,0,0,0,0,0,0,1],[0,0,1,0,0,0,0,0,1,0],[1,1,1,1,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,1],[0,0,0,0,0,0,1,0,1,1],[0,0,0,0,-1,0,0,0,0,1]])
constr_rhs = np.array([np.inf,8,1,1,1,2,1,2,0])
constr_lhs= np.array([26,4,-np.inf,-np.inf,-np.inf,1,-np.inf,-np.inf,-np.inf])
row_indices =np.arange(M)
col_indices = np.arange(N)

In [6]:
model.x=Var(col_indices,domain=Binary)
model.constraints=ConstraintList()


In [7]:
for i in row_indices:
  model.constraints.add(sum(constr_coef[i][j]*model.x[j] for j in col_indices)<=constr_rhs[i])
  model.constraints.add(sum(constr_coef[i][j]*model.x[j] for j in col_indices)>=constr_lhs[i])

In [8]:
model.objective=Objective(expr = summation(obj_coef,model.x),sense= maximize)

In [9]:
model.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   18 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

1 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True : Binary
          1 :     0 :  None :     1 : False :  True : Binary
          2 :     0 :  None :     1 : False :  True : Binary
          3 :     0 :  None :     1 : False :  True : Binary
          4 :     0 :  None :     1 : False :  True : Binary
          5 :     0 :  None :     1 : False :  True : Binary
          6 :     0 :  None :     1 : False :  True : Binary
          7 :     0 :  None :     1 : False :  True : Binary
    

In [10]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155676 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [11]:
opt=SolverFactory('cbc')

In [12]:
result = opt.solve(model)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 37.0
  Upper bound: 37.0
  Number of objectives: 1
  Number of constraints: 11
  Number of variables: 10
  Number of binary variables: 10
  Number of integer variables: 10
  Number of nonzeros: 10
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.05160689353942871
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.05160689353942871


In [13]:
# display solution
print('\nObjective = ', model.objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model.x[i].value)
print('\nConstraints')
model.constraints.display()


Objective =  37.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  1.0
x[ 6 ] =  1.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  0.0

Constraints
constraints : Size=18
    Key : Lower : Body : Upper
      1 :  None : 37.0 :  None
      2 :  26.0 : 37.0 :  None
      3 :  None :  7.0 :   8.0
      4 :   4.0 :  7.0 :  None
      5 :  None :  1.0 :   1.0
      6 :  None :  1.0 :  None
      7 :  None :  0.0 :   1.0
      8 :  None :  0.0 :  None
      9 :  None :  1.0 :   1.0
     10 :  None :  1.0 :  None
     11 :  None :  2.0 :   2.0
     12 :   1.0 :  2.0 :  None
     13 :  None :  1.0 :   1.0
     14 :  None :  1.0 :  None
     15 :  None :  2.0 :   2.0
     16 :  None :  2.0 :  None
     17 :  None : -1.0 :   0.0
     18 :  None : -1.0 :  None


$\huge{solution \ \ of  \ \ 2.3}$

$\huge{optimal \ \ value \ \ of \ \ objective \ \ function = 37.0}$
$\huge{optimal \ \ value \ \ of \ \ decision variable} \\ x_0 = 1 \\ x_1 = 0 \\ x_2 = 0 \\ x_3 = 1 \\ x_4 = 1 \\ x_5 = 1 \\ x_6 =1 \\ x_7 =1 \\ x_8 =1 \\ x_9 = 0 $


In [14]:
model1 = ConcreteModel()

In [15]:
model1.x=Var(col_indices)
model1.constraints=ConstraintList()

In [16]:
for i in row_indices:
  model1.constraints.add(sum(constr_coef[i][j]*model1.x[j] for j in col_indices)<=constr_rhs[i])
  model1.constraints.add(sum(constr_coef[i][j]*model1.x[j] for j in col_indices)>=constr_lhs[i])

In [17]:
model1.objective=Objective(expr = summation(obj_coef,model1.x),sense= maximize)

In [18]:
for i in col_indices:
  model1.x[i].setlb(0)
  model1.x[i].setub(1)

In [19]:
model1.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   18 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

1 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True :  Reals
          1 :     0 :  None :     1 : False :  True :  Reals
          2 :     0 :  None :     1 : False :  True :  Reals
          3 :     0 :  None :     1 : False :  True :  Reals
          4 :     0 :  None :     1 : False :  True :  Reals
          5 :     0 :  None :     1 : False :  True :  Reals
          6 :     0 :  None :     1 : False :  True :  Reals
          7 :     0 :  None :     1 : False :  True :  Reals
    

In [20]:
result = opt.solve(model1)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 37.0
  Upper bound: 37.0
  Number of objectives: 1
  Number of constraints: 12
  Number of variables: 11
  Number of nonzeros: 10
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.01
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 3
  Error rc: 0
  Time: 0.04971027374267578
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.04971027374267578


In [21]:
# display solution
print('\nObjective = ', model1.objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model1.x[i].value)
print('\nConstraints')
model1.constraints.display()


Objective =  37.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  1.0
x[ 6 ] =  1.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  0.0

Constraints
constraints : Size=18
    Key : Lower : Body : Upper
      1 :  None : 37.0 :  None
      2 :  26.0 : 37.0 :  None
      3 :  None :  7.0 :   8.0
      4 :   4.0 :  7.0 :  None
      5 :  None :  1.0 :   1.0
      6 :  None :  1.0 :  None
      7 :  None :  0.0 :   1.0
      8 :  None :  0.0 :  None
      9 :  None :  1.0 :   1.0
     10 :  None :  1.0 :  None
     11 :  None :  2.0 :   2.0
     12 :   1.0 :  2.0 :  None
     13 :  None :  1.0 :   1.0
     14 :  None :  1.0 :  None
     15 :  None :  2.0 :   2.0
     16 :  None :  2.0 :  None
     17 :  None : -1.0 :   0.0
     18 :  None : -1.0 :  None


$\huge{solution \ \ of \ \ 2.4}$  $\huge{optimal \ \ value \ \ of \ \ objective \ \ function = 37.0}$
$\huge{optimal \ \ value \ \ of \ \ decision variable} \\ x_0 = 1 \\ x_1 = 0 \\ x_2 = 0 \\ x_3 = 1 \\ x_4 = 1 \\ x_5 = 1 \\ x_6 =1 \\ x_7 =1 \\ x_8 =1 \\ x_9 = 0 $

$ \huge{solution \ \ of \ \ 2.5}$

MILP and LP solution is same here  because by hakim's theorem we always get optimal solution at nodes (heuristic approach) 
 
  
here we get same solution but it always not happend in some case if we round off may be solution is infeasible

$ \huge{ solution \ \ of \ \ 2.6 } $

let $x_{10}$ is new indicator variable such that

 $ x_{10}=1$ if we choose c10 course

 $x_{10} = 0 $ otherwise

 we add two new constraints as follows

 $x_5$ + $x_{10} \le 1 $

 $ x_6 +x_{10} \le 1 $ 

 by these change our objective function is also change as 

 $  max \sum c_i x_i $ $ \ \ \ \ \ \  \      i = 0,1,2,3,4,5,6,7,8,9,10  $

In [22]:
model.x10 = Var(domain=Binary)

In [23]:
model.new_objective =Objective(expr = summation(obj_coef,model.x) + 12*model.x10 , sense=maximize)

In [24]:
model.constraints.add(expr = model.x[5]+model.x10 <=1)
model.constraints.add(expr = model.x[6]+model.x10 <=1)

In [25]:
model.objective.deactivate()

In [26]:
model.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   20 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

2 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :   1.0 :     1 : False :  True : Binary
          1 :     0 :   0.0 :     1 : False :  True : Binary
          2 :     0 :   0.0 :     1 : False :  True : Binary
          3 :     0 :   1.0 :     1 : False :  True : Binary
          4 :     0 :   1.0 :     1 : False :  True : Binary
          5 :     0 :   1.0 :     1 : False :  True : Binary
          6 :     0 :   1.0 :     1 : False :  True : Binary
          7 :     0 :   1.0 :     1 : False :  True : Bin

In [27]:
result = opt.solve(model)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 45.0
  Upper bound: 45.0
  Number of objectives: 1
  Number of constraints: 13
  Number of variables: 11
  Number of binary variables: 11
  Number of integer variables: 11
  Number of nonzeros: 11
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.02531719207763672
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.02531719207763672


In [28]:
# display solution
print('\nObjective = ', model.new_objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model.x[i].value)
print('x10 = ',model.x10.value)
print('\nConstraints')
model.constraints.display()


Objective =  45.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  0.0
x[ 6 ] =  0.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  1.0
x10 =  1.0

Constraints
constraints : Size=20
    Key : Lower : Body : Upper
      1 :  None : 33.0 :  None
      2 :  26.0 : 33.0 :  None
      3 :  None :  6.0 :   8.0
      4 :   4.0 :  6.0 :  None
      5 :  None :  1.0 :   1.0
      6 :  None :  1.0 :  None
      7 :  None :  1.0 :   1.0
      8 :  None :  1.0 :  None
      9 :  None :  1.0 :   1.0
     10 :  None :  1.0 :  None
     11 :  None :  2.0 :   2.0
     12 :   1.0 :  2.0 :  None
     13 :  None :  1.0 :   1.0
     14 :  None :  1.0 :  None
     15 :  None :  2.0 :   2.0
     16 :  None :  2.0 :  None
     17 :  None :  0.0 :   0.0
     18 :  None :  0.0 :  None
     19 :  None :  1.0 :   1.0
     20 :  None :  1.0 :   1.0


$ \huge{solution \ \ of \ \ 2.7} $

 $\huge{optimal \ \ value \ \ of \ \ objective \ \ function = 45.0}$
$\huge{optimal \ \ value \ \ of \ \ decision variable} \\ x_0 = 1 \\ x_1 = 0 \\ x_2 = 0 \\ x_3 = 1 \\ x_4 = 1 \\ x_5 = 0 \\ x_6 =0 \\ x_7 =1 \\ x_8 =1 \\ x_9 = 1 \\ x_{10} = 1 $



In [29]:
model2 =ConcreteModel()

In [30]:
model2.x=Var(col_indices)
model2.x10 =Var()
model2.constraints=ConstraintList()

In [31]:
for i in row_indices:
  model2.constraints.add(sum(constr_coef[i][j]*model2.x[j] for j in col_indices)<=constr_rhs[i])
  model2.constraints.add(sum(constr_coef[i][j]*model2.x[j] for j in col_indices)>=constr_lhs[i])
model2.constraints.add(expr = model2.x[5]+model2.x10 <=1)
model2.constraints.add(expr = model2.x[6]+model2.x10 <=1)

In [32]:
model2.new_objective =Objective(expr = summation(obj_coef,model2.x) + 12*model2.x10 , sense=maximize)

In [33]:
for i in col_indices:
  model2.x[i].setlb(0)
  model2.x[i].setub(1)
model2.x10.setlb(0)
model2.x10.setub(1)

In [34]:
model2.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   20 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

2 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True :  Reals
          1 :     0 :  None :     1 : False :  True :  Reals
          2 :     0 :  None :     1 : False :  True :  Reals
          3 :     0 :  None :     1 : False :  True :  Reals
          4 :     0 :  None :     1 : False :  True :  Reals
          5 :     0 :  None :     1 : False :  True :  Reals
          6 :     0 :  None :     1 : False :  True :  Reals
          7 :     0 :  None :     1 : False :  True :  Re

In [35]:
result = opt.solve(model2)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 45.0
  Upper bound: 45.0
  Number of objectives: 1
  Number of constraints: 14
  Number of variables: 12
  Number of nonzeros: 11
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 6
  Error rc: 0
  Time: 0.024523496627807617
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.024523496627807617


In [36]:
# display solution
print('\nObjective = ', model2.new_objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model2.x[i].value)
print('x10 = ',model2.x10.value)
print('\nConstraints')
model2.constraints.display()


Objective =  45.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  0.0
x[ 6 ] =  0.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  1.0
x10 =  1.0

Constraints
constraints : Size=20
    Key : Lower : Body : Upper
      1 :  None : 33.0 :  None
      2 :  26.0 : 33.0 :  None
      3 :  None :  6.0 :   8.0
      4 :   4.0 :  6.0 :  None
      5 :  None :  1.0 :   1.0
      6 :  None :  1.0 :  None
      7 :  None :  1.0 :   1.0
      8 :  None :  1.0 :  None
      9 :  None :  1.0 :   1.0
     10 :  None :  1.0 :  None
     11 :  None :  2.0 :   2.0
     12 :   1.0 :  2.0 :  None
     13 :  None :  1.0 :   1.0
     14 :  None :  1.0 :  None
     15 :  None :  2.0 :   2.0
     16 :  None :  2.0 :  None
     17 :  None :  0.0 :   0.0
     18 :  None :  0.0 :  None
     19 :  None :  1.0 :   1.0
     20 :  None :  1.0 :   1.0




$ \huge{solution \ \ of \ \ 2.8}$

 $\huge{optimal \ \ value \ \ of \ \ objective \ \ function = 45.0}$
$\huge{optimal \ \ value \ \ of \ \ decision variable} \\ x_0 = 1 \\ x_1 = 0 \\ x_2 = 0 \\ x_3 = 1 \\ x_4 = 1 \\ x_5 = 0 \\ x_6 =0 \\ x_7 =1 \\ x_8 =1 \\ x_9 = 1 \\ x_{10} = 1 $


MILP and LP solution is same here  because by hakim's theorem we always get optimal solution at nodes (heuristic approach)

here we get same solution but it always not happend in some case if we round off may be solution is infeasible